services:
  blog-db:
    image: mysql:latest
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - blog-db-vol:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - blog-app-net
  blog-server:
    image: runipanda/blog-app:build-8187f98659f3f810513aedcf1a68b84d0c04c8ad
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--tries=1'
        - '--spider'
        - http://localhost:3000/health
      interval: 20s
      timeout: 5s
      retries: 5
    ports:
      - '3001:3000'
    environment:
      - DB_HOST=blog-db
      - DB_USER_FILE=/run/secrets/db_username
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_NAME=blogdb
      - NODE_HOST="{{.Node.Hostname}}"
    depends_on:
      - blog-db
    networks:
      - blog-app-net
    secrets:
      - db_password
      - db_username
volumes:
  blog-db-vol: null
networks:
  blog-app-net: null
secrets:
  db_password:
    external: true
  db_username:
    external: true
