name: Bloggy CD
on:
    push:
        branches: ['main']
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            IMAGE_NAME: runipanda/blog-app
            IMAGE_TAG: build-${{github.sha}} #runipanda/blog-app:build-1
        steps:
            - name: Checkout the source code
              uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - name: Build docker image
              run: docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} --platform linux/amd64 .
            - name: Login into Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_PASSWORD}}
            - name: Push docker image to Docker Hub
              run: docker push ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}

            - name: Update compose yaml
              uses: fjogeleit/yaml-update-action@v0.16.0
              with:
                  valueFile: compose.yaml
                  propertyPath: 'services["blog-server"].image'
                  value: ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
                  commitChange: false
            - name: Commit the changes
              run: |
                  git config --local user.name github-actions
                  git config --local user.email github-action@github.com
                  git add .
                  git commit -m "✨😍 successful deployment updated the image tag ${{env.IMAGE_TAG}}"
            - name: Push commit
              run: |
                 git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
                 git push origin main

    deploy:
        name: Deploy the image to Docker Swarm Cluster
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: runipanda/blog-app
            IMAGE_TAG: build-${{github.sha}}
        needs:
            - build-and-push
        steps:
            - name: SSH into the server
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{secrets.SWARM_MAMAGER_HOST}}
                  username: ${{secrets.SWARM_MANAGER_USERNAME}}
                  key: ${{secrets.SWARM_MANAGER_SSH_KEY}}
                  port: ${{secrets.SWARM_MANAGER_PORT}}
                  script: |
                      set -e
                      cd ~/bloggy

                      # pull compose file using git
                      git fetch origin main
                      git checkout origin/main

                      docker pull ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
                      docker stack deploy -c compose.yaml bloggy
